let data = [
  'Bitcoin (BTC)',
  'Ethereum (ETH)',
  'Binance Coin (BNB)',
  'Tether (USDT)',
  'Solana (SOL)',
  'Cardano (ADA)',
  'XRP (XRP)',
  'USD Coin (USDC)',
  'Polkadot (DOT)',
  'Terra (LUNA)',
  'Dogecoin (DOGE)',
  'Avalanche (AVAX)',
  'SHIBA INU (SHIB)',
  'Polygon (MATIC)',
  'Crypto.com Coin (CRO)',
  'Binance USD (BUSD)',
  'Wrapped Bitcoin (WBTC)',
  'Litecoin (LTC)',
  'Uniswap (UNI)',
  'Algorand (ALGO)',
  'Chainlink (LINK)',
  'TRON (TRX)',
  'Bitcoin Cash (BCH)',
  'TerraUSD (UST)',
  'Stellar (XLM)',
  'Decentraland (MANA)',
  'Axie Infinity (AXS)',
  'Dai (DAI)',
  'VeChain (VET)',
  'FTX Token (FTT)',
  'Elrond (EGLD)',
  'Internet Computer (ICP)',
  'Cosmos (ATOM)',
  'Filecoin (FIL)',
  'Ethereum Classic (ETC)',
  'Bitcoin BEP2 (BTCB)',
  'NEAR Protocol (NEAR)',
  'THETA (THETA)',
  'Hedera (HBAR)',
  'The Sandbox (SAND)',
  'Tezos (XTZ)',
  'Fantom (FTM)',
  'Monero (XMR)',
  'BitTorrent (BTT)',
  'EOS (EOS)',
  'Klaytn (KLAY)',
  'The Graph (GRT)',
  'UNUS SED LEO (LEO)',
  'IOTA (MIOTA)',
  'Loopring (LRC)',
  'Gala (GALA)',
  'Helium (HNT)',
  'Flow (FLOW)',
  'PancakeSwap (CAKE)',
  'Stacks (STX)',
  'Bitcoin SV (BSV)',
  'Maker (MKR)',
  'Aave (AAVE)',
  'Kusama (KSM)',
  'Amp (AMP)',
  'eCash (XEC)',
  'Enjin Coin (ENJ)',
  'Zcash (ZEC)',
  'Harmony (ONE)',
  'Neo (NEO)',
  'Waves (WAVES)',
  'Quant (QNT)',
  'THORChain (RUNE)',
  'Chiliz (CHZ)',
  'Basic Attention Token (BAT)',
  'Kadena (KDA)',
  'KuCoin Token (KCS)',
  'Curve DAO Token (CRV)',
  'Holo (HOT)',
  'OKB (OKB)',
  'Arweave (AR)',
  'Huobi Token (HT)',
  'Dash (DASH)',
  'Celo (CELO)',
  'Compound (COMP)',
  'Nexo (NEXO)',
  'Theta Fuel (TFUEL)',
  'Decred (DCR)',
  'NEM (XEM)',
  'TrueUSD (TUSD)',
  'Mina (MINA)',
  'Qtum (QTUM)',
  'Voyager Token (VGX)',
  '1inch Network (1INCH)',
  'IoTeX (IOTX)',
  'WAX (WAXP)',
  'Immutable X (IMX)',
  'OMG Network (OMG)',
  'Ankr (ANKR)',
  'XDC Network (XDC)',
  'Pax Dollar (USDP)',
  'Ravencoin (RVN)',
  'ICON (ICX)',
  'Oasis Network (ROSE)',
  'Siacoin (SC)'
]

let sym = [
    "BTC",
    "ETH",
    "BNB",
    "USDT",
    "SOL",
    "ADA",
    "XRP",
    "USDC",
    "DOT",
    "LUNA",
    "DOGE",
    "AVAX",
    "SHIB",
    "MATIC",
    "CRO",
    "BUSD",
    "WBTC",
    "LTC",
    "UNI",
    "ALGO",
    "LINK",
    "TRX",
    "BCH",
    "UST",
    "XLM",
    "MANA",
    "AXS",
    "DAI",
    "VET",
    "FTT",
    "EGLD",
    "ICP",
    "ATOM",
    "FIL",
    "ETC",
    "BTCB",
    "NEAR",
    "THETA",
    "HBAR",
    "SAND",
    "XTZ",
    "FTM",
    "XMR",
    "BTT",
    "EOS",
    "KLAY",
    "GRT",
    "LEO",
    "MIOTA",
    "LRC",
    "GALA",
    "HNT",
    "FLOW",
    "CAKE",
    "STX",
    "BSV",
    "MKR",
    "AAVE",
    "KSM",
    "AMP",
    "XEC",
    "ENJ",
    "ZEC",
    "ONE",
    "NEO",
    "WAVES",
    "QNT",
    "RUNE",
    "CHZ",
    "BAT",
    "KDA",
    "KCS",
    "CRV",
    "HOT",
    "OKB",
    "AR",
    "HT",
    "DASH",
    "CELO",
    "COMP",
    "NEXO",
    "TFUEL",
    "DCR",
    "XEM",
    "TUSD",
    "MINA",
    "QTUM",
    "VGX",
    "1INCH",
    "IOTX",
    "WAXP",
    "IMX",
    "OMG",
    "ANKR",
    "XDC",
    "USDP",
    "RVN",
    "ICX",
    "ROSE",
    "SC"
]

let logos = [    
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1027.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1839.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/825.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5426.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2010.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/52.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3408.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6636.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4172.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/74.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5805.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5994.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3635.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4687.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3717.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/7083.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4030.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1975.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1958.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1831.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/7129.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/512.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1966.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6783.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4943.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3077.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4195.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6892.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/8916.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3794.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2280.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1321.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4023.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6535.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2416.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4642.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6210.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2011.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3513.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/328.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3718.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1765.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4256.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6719.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3957.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1934.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1720.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/7080.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5665.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4558.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/7186.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4847.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3602.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1518.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/7278.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5034.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6945.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/10791.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2130.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1437.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3945.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1376.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1274.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3155.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4157.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1697.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/4066.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5647.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2087.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/6538.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2682.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3897.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2502.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5632.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/131.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5567.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/5692.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3822.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2694.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/873.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1168.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2563.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/8646.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1684.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/8104.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1817.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2777.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/10603.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2300.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1808.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2634.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3783.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2577.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/3330.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/2099.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/7653.png",
  "https://s2.coinmarketcap.com/static/img/coins/64x64/1042.png"
]

module.exports = {data,sym,logos}